shady.set("spatial_mode", true)
shady.set("physics_enabled", false)
shady.set("fps_mode", false)
shady.set("sky", false)
shady.modules({ ["physics"] = false, ["fps"] = false, ["lua"] = true })
shady.plugins.path(assert(os.getenv("SHADY_TEST_PLUGIN_DIR")))
shady.plugins.load("frozen-window")
