shady.set("spatial_mode", true)
shady.set("window_wobble", false)
shady.set("physics_enabled", false)
shady.set("fps_mode", false)
shady.set("close_animation", false)
shady.set("sky", false)
shady.set("environment", false)
shady.bind("fps_toggle", "Super+f")
shady.bind("debug_ray", "F5")
shady.plugin(assert(os.getenv("SHADY_REPRESENTATION_TEST_PLUGIN")))
