local name = assert(os.getenv("SHADY_CAPTURE_PLUGIN"))
local root = assert(os.getenv("SHADY_ROOT"))
shady.set("spatial_mode", true)
shady.set("fps_mode", name:match("^fps%-") ~= nil)
shady.set("physics_enabled", false)
shady.set("window_gravity", false)
shady.set("window_wobble", name == "window-motion")
shady.set("window_titlebar", true)
shady.set("window_titlebar_height", 28.0)
shady.set("window_corner_radius", 12.0)
shady.set("window_border_width", 3.0)
shady.set("window_border_color", "#284052")
shady.set("window_border_focus_color", "#FFB070")
shady.set("window_titlebar_color", "#101824")
shady.set("window_titlebar_focus_color", "#302333")
shady.set("window_titlebar_text_color", "#F8E7DC")
shady.set("window_opacity", 1.0)
shady.set("window_brightness", 1.0)
shady.set("window_effect_strength", 0.0)
shady.set("shadows", true)
shady.set("floor", true)
shady.set("floor_base_color", "#0B101B")
shady.set("floor_grid_color", "#937CCF")
shady.set("floor_grid_strength", 0.18)
shady.set("background_top", "#090C17")
shady.set("background_horizon", "#30213D")
shady.set("background_bottom", "#080B13")
shady.set("sky", false)
shady.modules({physics = false, fps = true, lua = true,
    ["close-animation"] = true, ["scene-effects"] = true})
if name == "obj-loader" then
    shady.set("environment", true)
    shady.set("environment_path", root .. "/assets/test-room.obj")
end
if name ~= "obj-loader" and name ~= "window-motion" then
    shady.plugins.load(name)
end
