-- Astral Loom: a procedural energy observatory and live spatial panels.
local root = os.getenv("SHADY_ROOT") or "."
local build = os.getenv("SHADY_ASTRAL_BUILD_DIR") or (root .. "/build")
shady.set("spatial_mode", true)
shady.set("physics_enabled", false)
shady.set("window_gravity", false)
shady.set("window_wobble", false)
shady.set("fps_mode", true)
shady.set("window_sides", false)
shady.set("shadows", false)
shady.set("floor", false)
shady.set("sky", false)
shady.set("environment_obj", false)
shady.set("window_tint", "#FFFFFF")
shady.set("window_brightness", 1.05)
shady.set("window_effect_strength", 0.0)
shady.set("window_opacity", 1.0)
shady.set("window_border_focus_color", "#52EAFF")
shady.set("window_titlebar_color", "#101024")
shady.set("window_titlebar_focus_color", "#19364D")
shady.modules({["window-motion"] = true, ["physics"] = false,
    ["fps"] = true, ["scene-effects"] = true, ["lua"] = true})
shady.plugin(build .. "/libshady-plugin-astral-loom.so")
shady.bind("quit", "Super+Shift+Escape")
shady.bind("close_window", "Super+q")
shady.bind("cycle_windows", "Super+Tab")
shady.bind("fps_toggle", "Super+f")
shady.bind("fps_capture", "Super+Shift+f")
shady.bind("camera_reset", "Super+0")
shady.bind("camera_zoom_in", "Super+equal")
shady.bind("camera_zoom_out", "Super+minus")
